[package]
name = "hnz"
version = "0.1.0"
edition = "2021"
description = "hnz development repository"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecs = { path = "ecs" }
wgfx = { path = "wgfx" }
physics = { path = "physics" }