[package]
name = "wsh_window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hnz = { path = "../../../hnz" }
simple_logger = "4.3.0"